### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tadatuta** [tadatuta/bem-dist-server#1]
- [x] показывать блоки из bem-core
- [x] давать возможность выбрать платформу
- [ ] предлагать, какие именно технологии необходимо собрать
- [ ] уметь собирать dist по bemdecl/deps/bemjson
- [ ] уметь генерить html, если задан bemjson
- [x] уметь отдавать dist в архиве
- [x] шорткат, чтобы ставить/снимать все галки сразу
- [ ] уметь опционально отключать элементы/модификаторы
- [ ] по депсам автоматически взводить галки по зависимостям (?)
- [ ] попробовать унести фичу filter в официальный levels-to-bemdecl
- [x] собирать морду отдельно от диста (и пересмотреть подход: генерировать bemjson в desktop.bundles и запускать make)
- [ ] подумать про разные версии библиотек
- [ ] подумать про альтернативу инлайнингу картинок (?)
- [x] выпилить остатки bem-tools
- [ ] отрефакторить код
- [ ] причесать readme
- [ ] продумать деплой

**Comment by tavriaforever** [comment]
Добавить лейблу чекбокса `user-select: none;` 
Выбираешь пару раз туда-сюда и пол страницы выделился текст

**Comment by tavriaforever** [comment]
Сделать либы колонками, привет `flexbox`

**Comment by tavriaforever** [comment]
Возможность тоглить блоки одной библиотеки

**Comment by tavriaforever** [comment]
Добавить возможность сохранять выбранный набор на случай, если в существующий проект потребовался еще какой-то блок, а всех блоков не помнишь/не хочешь добавлять. Можно класть куда в браузер клиента либо в файлик, либо еще как-то.

**Comment by tavriaforever** [comment]
Добавить инфу о том, как можно сюда добавить свою либу

**Comment by tavriaforever** [comment]
Сделать название библиотек/блоков ссылками на репозиторий/страницу библиотеки/блока

**Comment by tavriaforever** [comment]
Добавить инфу о том, что билдер `умный` и добавить в сборку минимум всего, чтобы оно работало.

**Comment by Guria** [comment]
как на счёт npm бинарника?
